name: sar_autoencoder_complete
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # Python base
  - python=3.10
  
  # Core dependencies for SAR patch creation
  - rasterio>=1.4.0
  - numpy>=1.21.0
  - scikit-learn>=1.0.0
  - pyyaml>=6.0
  - tqdm>=4.60.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  
  # PyTorch ecosystem (with CUDA support)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - pytorch-cuda=11.8
  
  # Image processing and computer vision
  - opencv>=4.5.0
  - pillow>=8.0.0
  - imageio>=2.9.0
  - skimage>=0.19.0
  
  # Data analysis and visualization
  - pandas>=1.3.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - bokeh>=2.4.0
  - ipywidgets>=7.6.0
  
  # Machine Learning enhancements
  - albumentations>=1.3.0
  - tensorboard>=2.8.0
  - wandb>=0.12.0
  
  # Optimization and hyperparameter tuning
  - optuna>=3.0.0
  - hyperopt>=0.2.7
  
  # Logging and monitoring
  - colorlog>=6.0.0
  - rich>=10.0.0
  - loguru>=0.6.0
  
  # Parallelization and performance
  - joblib>=1.1.0
  - numba>=0.56.0
  - dask>=2022.0.0
  
  # Development and testing
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipykernel>=6.0.0
  - pytest>=6.0.0
  - black>=21.0.0
  - flake8>=4.0.0
  
  # Geospatial dependencies
  - geopandas>=0.10.0
  - shapely>=1.8.0
  - fiona>=1.8.0
  - pyproj>=3.2.0
  - folium>=0.12.0
  
  # Additional useful packages
  - requests>=2.25.0
  - click>=8.0.0
  - pathlib2>=2.3.0
  - psutil>=5.8.0
  - h5py>=3.1.0
  - netcdf4>=1.5.0
  
  # Pip-only dependencies
  - pip
  - pip:
    # SAR-specific packages
    - pysentinelsat>=1.1.0
    - eodag>=2.5.0
    - sentinelhub>=3.4.0
    
    # Advanced ML packages
    - timm>=0.6.0
    - transformers>=4.15.0
    - lightning>=1.8.0
    - torchmetrics>=0.11.0
    
    # Additional image processing
    - imageio-ffmpeg>=0.4.5
    - rawpy>=0.17.0
    
    # Advanced logging
    - multiprocessing-logging>=0.3.0
    - structlog>=21.0.0
    
    # Additional optimization
    - bayesian-optimization>=1.4.0
    - nevergrad>=0.4.0
    
    # Utilities
    - fire>=0.4.0
    - hydra-core>=1.1.0
    - omegaconf>=2.1.0
    
    # Performance profiling
    - line-profiler>=3.5.0
    - memory-profiler>=0.60.0
    
    # Additional visualization
    - plotnine>=0.8.0
    - altair>=4.2.0
